### ISSUE TITLE
Créer un menu

### ISSUE THREAD

**Issue by bertrandkeller** [bertrandkeller/goHugo-learn#6]
### Préambule

Le menu est l‘autre manière d’afficher des listes (ou index) de pages. Le menu reste un élément de navigation tendancieux des systèmes de gestions de contenus. En effet, il n’a rien d'automatique car, que ce soit la liste des liens ou encore l'ordre des liens, il est sujet à un choix arbitraire n'ayant souvent aucun rapport avec la position dans une arborescence, la première lettre du nom du lien, ou la date de création.

Il existe donc plusieurs manières de créer des menus. On devra à mettre en place des paramètres (dans le front matter ou `config.toml`) pour gérer la liste des liens de chaque menu et l’ordre des liens.

### Exercice

1.  Création des pages de contenus
    - Créer des pages de contenu à la racine de `content` ex. `about.md`
2.  Menu : https://gohugo.io/templates/menu-templates/
    -   Configurer la liste des éléments de menu dans le fichier `config.toml`
    -   Afficher le code pour afficher ce menu dans le fichier `themes/wonderfull/layouts/_default/baseof.html`

### Aide pour le code

**config.toml**
```
menu:
  main:
  - identifier: blog
    name: This is the blog section
    title: blog section
    url: /post/
    weight: -110
  - identifier: about
    name: This is the about page
    title: about
    url: /about/
    weight: 110
```

_Il est possible d’ajouter ces bouts de code directement dans le front Matter de la page. C’est plus cohérent de le mettre dans la page, mais certaines modifications du menu demandent d’ouvrir plusieurs fichiers (au lieu d‘un seul dans ce cas)._

**themes/wonderfull/layouts/_default/baseof.html**
```
<ul>
{{ range .Site.Menus.main }}
<li>
    <a href="{{ .URL }}">{{ .Name }}</a>
</li>
{{ end }}
</ul>
```
